image: node:argon

variables:
  GIT_SSL_NO_VERIFY: "1"

pages:
  cache:
    paths:
    - bower_components/
  script:
  - npm install -g bower
  - bower install --allow-root
  - mkdir public
  - sed -i 's|base\ href=\"/\"|base\ href=\"/editor/\"|' index.html
  - cp -r css icons img js templates index.html favicon.ico bower_components public/
  artifacts:
    paths:
    - public
  only:
    - master
